module.exports = {
  PAGE_SIZE: 10,
  GENRES: [
    'Adventure',
    ' Family',
    ' Fantasy',
    ' Musical',
    'Action',
    ' Adventure',
    ' Sci-Fi',
    ' Drama',
    ' War',
    'Horror',
    ' Mystery',
    ' Thriller',
    ' Horror',
    'Drama',
    ' Romance',
    'Animation',
    'Crime',
    ' History',
    ' Western',
    ' Film-Noir',
    'Thriller',
    'Fantasy',
    'Musical',
    ' Comedy',
    ' Documentary',
    ' Music',
    'Comedy',
    'Short',
    ' Action',
    'Family',
    ' Sport',
    ' Crime',
    'Mystery',
    ' Short',
    'Talk-Show',
    ' Biography',
    'Biography',
    'Romance',
    'Game-Show',
    'Western',
    'Documentary',
    ' News',
    ' Talk-Show',
    'Adult',
    'Film-Noir',
    ' Reality-TV',
  ],
};
